onlineShop/onlineShop/Controllers/CartController.cs
using onlineShop.DAO;
using onlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using onlineShop.Models.EF;
using onlineShop.Models.DAO;
using onlineShop.Security;

namespace onlineShop.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";

        // GET: /Cart/
        //   [Authorize]
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;

            }
            return View(list);
        }

        public ActionResult AddItem(string MaSP, int SoLuong)
        {
            if (onlineShop.Security.SessesionPersister.User == null)
                return RedirectToAction("DangNhap", "User");
            else
            {
                var sanPham = new SanPhamDao().ViewDetail(MaSP);
                var cart = Session[CartSession];
                if (cart != null)
                {
                    var list = (List<CartItem>)cart;
                    if (list.Exists(x => x.sp.MaSP == MaSP))
                    {
                        foreach (var item in list)
                        {
                            if (item.sp.MaSP == MaSP)
                            {
                                item.SoLuong += SoLuong;
                            }
                        }
                    }
                    else
                    {
                        //tao moi doi tuong cartitem
                        var item = new CartItem();
                        item.sp = sanPham;
                        item.SoLuong = SoLuong;
                        list.Add(item);
                    }

                    //gan vao session
                    Session[CartSession] = list;
                }
                else
                {
                    //tao moi doi tuong cartitem
                    var item = new CartItem();
                    item.sp = sanPham;
                    item.SoLuong = SoLuong;
                    var list = new List<CartItem>();
                    list.Add(item);
                    //gan vao session
                    Session[CartSession] = list;
                }
                return RedirectToAction("Index");
            }
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];
            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.sp.MaSP == item.sp.MaSP);
                if (jsonItem != null)
                {
                    item.SoLuong = jsonItem.SoLuong;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult Delete(string id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.sp.MaSP == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            ViewBag.ngaymua = DateTime.Now;
            int tien = 0;
            if (cart != null)
            {
                list = (List<CartItem>)cart;
                foreach (var item in list)
                {
                    tien += Convert.ToInt32(item.sp.GiaMoi.GetValueOrDefault(0) * item.SoLuong);
                }
                ViewBag.tongtien = tien;
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Payment(string ghichu, string ngaymua, int tongtien)
        {
            
            var hoadon = new HoaDon();
            hoadon.NgayMua = DateTime.Now;
            hoadon.TongTien = tongtien;
            hoadon.GhiChu = ghichu;
            hoadon.MaHD = new HoaDonDao().SetMHD();
            hoadon.MaKH = Convert.ToInt32(Session["UserId"]);
            
            var id = new HoaDonDao().Insert(hoadon);
            var cart = (List<CartItem>)Session[CartSession];
            var ChiTietDao = new ChiTietHDDao();
            foreach (var item in cart)
            {
                var CThoadon = new ChiTietHD();
                CThoadon.MaSP = item.sp.MaSP;
                CThoadon.MaHD = id;
                CThoadon.SoLuong = item.SoLuong;
                CThoadon.ThanhTien = item.sp.GiaMoi * item.SoLuong;
                ChiTietDao.Insert(CThoadon);
            }
            new OnlineShopDbContext().SaveChanges();
            return RedirectToAction("Success");
        }
        public ActionResult Success()
        {
            Session[CartSession] = null;
            return View();
        }
    }
}

onlineShop/onlineShop/Controllers/ChiTietSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using onlineShop.Models.EF;
using onlineShop.DAO;

namespace onlineShop.Controllers
{


    public class ChiTietSanPhamController : Controller
    {
        //
        // GET: /ChiTietSanPham/

        //xem chi tiet
        public ActionResult XemChiTiet(string MaSP)
        {

            SanPham sp = new SanPhamDao().ViewDetail(MaSP);
            var DoiTuong = sp.DoiTuong;
            var MaPL = sp.MaPL;
            ViewBag.SanPhamCungLoai = new SanPhamDao().laysp(DoiTuong, MaPL, 1, 4);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }
    }
}

onlineShop/onlineShop/Views/ChiTietSanPham/XemChiTiet.cshtml
@model onlineShop.Models.EF.SanPham
@{
    ViewBag.Title = "XemChiTiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content-oneproduct">
    <div class="container">
        <!-- ===== Tên sản phẩm ===== -->
        <div class="product-name">
            <div class="row">
                <h5 id="name-item"><b>@Model.TenSP</b></h5>
                <a href="#" id="share-face"><i class="fa fa-facebook-official"></i> Chia sẻ</a>
            </div>
        </div>
        <!-- ===== /Tên sản phẩm ===== -->
        <div class="row chi_tiet">
            <!-- ===== Ảnh sản phẩm ===== -->
            <div class="col-md-4">
                <div id="image-product">
                    <img src= @Model.Anh alt="@Model.TenSP">
                </div>
            </div>
            <!-- ===== /Ảnh sản phẩm ===== -->
            <!-- ===== Thông tin sản phẩm -->
            <div class="col-md-4">
                <div class="tt-sp">
                    <ul>
                        <li>Sản phẩm được làm từ nilon chất lượng cao của Trung Quốc</li>
                        <li>Màu sắc đa dạng phong phú</li>
                        <li>Thân thiện với môi trường</li>
                        <li>Không gây hại đến sức khỏe người sử dụng</li>
                    </ul>
                </div>
                <div class="gia">
                    <h5>@Model.GiaMoi VNĐ</h5>
                </div>
                <div class="btn-mua">
                    <button class="btn btn-success" id="btnInsert" onclick="window.location.href='@Url.Action("AddItem", "Cart", new { @MaSP = @Model.MaSP, @SoLuong = 1 })'"><b>THÊM VÀO GIỎ HÀNG</b></button>
                </div>
            </div>
            <!-- ===== /Thông tin sản phẩm =====-->
        </div> <!-- /end row chi-tiet -->
        <h5 class="text-center">CÓ THỂ BẠN QUAN TÂM</h5>

        <!-- ===== slide sp tương tự =====-->
        <div class="row">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">

                        @foreach (var item in ViewBag.SanPhamCungLoai)
                        {
                            <div class="col-md-3">
                                <a href="@Url.Action("XemChiTiet", "ChiTietSanPham", new { @MaSP = item.MaSP, @TenSP = item.TenSP })">
                                    <div class="thumbnail">
                                        <img src=@item.Anh alt="@item.TenSP">
                                        <div class="">
                                            <p>@item.TenSP</p>
                                            <p class="">@item.GiaMoi VNĐ</p>
                                        </div>
                                        <div class="btn-buy">
                                            <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("XemChiTiet", "ChiTietSanPham", new { @MaSP = item.MaSP, @TenSP = item.TenSP })'"><b>XEM CHI TIẾT</b></button>

                                        </div>
                                    </div>
                                </a>
                            </div> <!-- end 1 items -->
                        }

                    </div>
                    <div class="item">
                        @foreach (var item in ViewBag.SanPhamCungLoai)
                        {
                            <div class="col-md-3">
                                <a href="@Url.Action("XemChiTiet", "ChiTietSanPham", new { @MaSP = item.MaSP, @TenSP = item.TenSP })">
                                    <div class="thumbnail">
                                        <img src= @item.Anh alt= @item.TenSP>
                                        <div class="">
                                            <p>@item.TenSP</p>
                                            <p class="">@item.GiaMoi VNĐ</p>
                                        </div>
                                        <div class="btn-buy">
                                            <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("XemChiTiet", "ChiTietSanPham", new { @MaSP = item.MaSP, @TenSP = item.TenSP })'"><b>XEM CHI TIẾT</b></button>

                                        </div>
                                    </div>
                                </a>
                            </div> <!-- end 1 items -->
                        }
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <!-- ===== end slide sp tương tự =====-->
    </div>
</div>